### ISSUE TITLE
Windows clone fails because of empty file "etc/hadoop/hadoop-env."

### ISSUE THREAD

**Issue by PKRoma** [confluentinc/kafka-connect-blog#1]
You cannot clone this repository to a Windows box because on Windows it's not possible to name a file with a trailing '.' and this repository contains the file (note the trailing '.'):

etc/hadoop/hadoop-env.

This file is in fact empty and probably therefore not needed.

Can you please delete this file to allow Windows clones of this repository?

**Comment by Ishiihara** [comment]
@PKRoma Thank you for reporting this. I have updated the repo to remove the unused file. Let me know if this resolves your issue.
